### ISSUE TITLE
断网了？断网了？为什么？为什么？

### ISSUE THREAD

**Issue by jianchao123** [freefq/free#580]

**Comment by zzj121** [comment]
用不了就不用 从 Windows 版邮件发送 发件人: Crazy发送时间: 2023年6月4日 11:28收件人: freefq/free抄送: Subscribed主题: Re: [freefq/free] 断网了？断网了？为什么？为什么？ (Issue #580) Closed #580 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
